version: "2.29.1"

name: smm_shelter

services:
  frontend:
    container_name: ss-frontend
    restart: always
    build: ./frontend
    env_file: .env

  backend:
    container_name: ss-backend
    # restart: always
    build: ./backend
    env_file: .env
    volumes:
      - ./backup:/backup
      - ./storage:/storage
    depends_on:
      - database


  database:
    container_name: ss-postgres
    restart: always
    image: postgres:16
    volumes:
      - ./backup/dump_pets.sql:/docker-entrypoint-initdb.d/dump_pets.sql
    env_file: .env

  nginx:
    container_name: ss-nginx
    restart: always
    image: nginx:1.25.4
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d

      - ./storage:/storage
    ports:
      - 8002:3000
      - 8003:8000
    depends_on:
      - backend
      - frontend
