version: "2.27"

name: smm_shelter

services:
  smm_shelter-frontend:
    container_name: smm_shelter-frontend
    restart: always
    build: ./frontend

  smm_shelter-backend:
    container_name: smm_shelter-backend
    restart: always
    build: ./backend
    environment:
      - POSTGRES_NAME_SERVICE=smm_shelter-postgres
    volumes:
      - ./storage:/storage
    depends_on:
      - smm_shelter-postgres


  smm_shelter-postgres:
    container_name: smm_shelter-postgres
    restart: always
    image: postgres:16
    volumes:
      - ./dump/dump_pets.sql:/docker-entrypoint-initdb.d/dump_pets.sql
    environment:
      - POSTGRES_DB=pets-service
      - POSTGRES_HOST_AUTH_METHOD=trust

  smm_shelter-nginx:
    container_name: smm_shelter-nginx
    image: nginx:1.25.4
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d

      - ./storage:/storage
    ports:
      - 8002:3000
      - 8003:8000
    depends_on:
      - smm_shelter-backend
      - smm_shelter-frontend
