version: "2.27"

name: smm_shelter

services:
  # smm_shelter-admin_panel:
  #   container_name: admin_panel
  #   restart: always
  #   build: admin_panel
  #   # environment:
  #   #   - BACKEND_LINK=0.0.0.0:8002
  #   ports:
  #     - 8080:8080
  #   # depends_on:
  #   #   - backend


  smm_shelter-frontend:
    container_name: smm_shelter-frontend
    restart: always
    build: ./frontend

  smm_shelter-backend:
    container_name: smm_shelter-backend
    restart: always
    build: ./backend
    environment:
      - POSTGRES_NAME_SERVICE=smm_shelter-postgres
      - POSTGRES_DB=pets-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./storage:/storage
    depends_on:
      - smm_shelter-postgres


  smm_shelter-postgres:
    container_name: smm_shelter-postgres
    restart: always
    image: postgres:16
    volumes:
      - ./dump/dump_pets.sql:/docker-entrypoint-initdb.d/dump_pets.sql
    environment:
      - POSTGRES_DB=pets-service
      - POSTGRES_HOST_AUTH_METHOD=trust

  smm_shelter-nginx:
    container_name: smm_shelter-nginx
    image: nginx:1.25.4
    volumes:
      - ./nginx/hello.txt:/service/hello.txt
      - ./nginx/robots.txt:/service/robots.txt
      - ./nginx/sitemap.xml:/service/sitemap.xml

      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./storage:/storage
    ports:
      - 8002:8002
    depends_on:
      - smm_shelter-backend
      - smm_shelter-frontend
