version: "2.27"

name: smm_shelter

services:
  # admin_panel:
  #   container_name: admin_panel
  #   restart: always
  #   build: admin_panel
  #   # environment:
  #   #   - BACKEND_LINK=0.0.0.0:8002
  #   ports:
  #     - 8080:8080
  #   # depends_on:
  #   #   - backend


  frontend:
    container_name: frontend
    restart: always
    build: ./frontend

  backend:
    container_name: backend
    restart: always
    build: ./backend
    environment:
      - POSTGRES_NAME_SERVICE=postgres-pets-service
      - POSTGRES_DB=pets-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./storage:/storage
    depends_on:
      - postgres-pets-service


  postgres-pets-service:
    container_name: postgres-pets-service
    restart: always
    image: postgres:16
    volumes:
      - ./dump/dump_pets.sql:/docker-entrypoint-initdb.d/dump_pets.sql
    environment:
      - POSTGRES_DB=pets-service
      - POSTGRES_HOST_AUTH_METHOD=trust

  nginx:
    image: nginx:1.25.4
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - web:/app/dist
      - ./storage:/storage
    ports:
      - 8002:8002
    depends_on:
      - backend
      - frontend
  

volumes:
  data:
    driver: local
  web:
