name: Docker Compose Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./compose.yaml"

      - name: Execute tests in the running services
        run: |
          sudo apt-get install curl
          curl localhost:8002

      - name: 🚀 deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/matv864/smm_shelter
            sudo git fetch --all
            sudo git reset --hard origin/main
            sudo docker compose up -d --build
